title: 'Sw1tchmode'
description: "i don't know why i keep switching"
baseurl: ""
url: "sw1tchmode.github.io"

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

style: dark

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
