title: 'Sw1tchmode'
description: "i don't know why i keep switching"
baseurl: ""
url: "sw1tchmode.github.io"

header_pages:
  - index.md
  - writeup.md
  - about.md

style: dark

footer: 'follow me on <a href="https://twitter.com/Fr33sTYLeR_DJ">twitter</a>'
collections:
  writeups:
    output: true
    permalink: /writeup/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: page

# Build settings
markdown: kramdown
remote_theme: Sw1tchmode/jekyll-theme-console
